adeva_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(pattern_name='admin:index'), name='home'),
    path('admin/', admin.site.urls),
    path('', include('movimentos.urls', namespace="movimentos"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

movimentos/urls.py
from django.urls import path
from . import views
from .models import MovimentosCaixa
from django.contrib import admin
from .views import ReciboPDF



app_name = 'movimentos'
 
urlpatterns = [
     path('', views.movimentos_caixa_list, name="movimentos_caixa_list"),
     path('fechamento/', views.fechamento_view, name='fechamento'),
     path('download/', views.view_download, name='download'),
     path('relatorio-fechamento/', views.rel_fechamento_view, name='relatorio_fechamento'),
     path('download-arquivos/', views.download_documentos, name='download_arquivos'),
     path('gerar-pdf/', ReciboPDF.as_view(), name='gerar-pdf'),
     path('gerar-excel/', views.gerar_excel, name='gerar-excel'),
     path('relatorio-detalhado/', views.rel_detalhado, name='relatorio_detalhado'),
     path('relatorio-final-detalhado/', views.rel_final_detalhado, name='relatorio_final_detalhado'),
     #path('test/', views.test_view, name='test'),
]

movimentos/models.py
from django.db import models
from configuracoes.models import *
from pessoas.models import Pessoa, DadosPgto
from django.contrib import admin
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone
import os
import unicodedata
from django.conf import settings
import random


def sanitize_filename(filename):
    # Substituir espaços por underscores
    filename = filename.replace(' ', '_')

    # Remover acentos e caracteres especiais
    filename = unicodedata.normalize('NFKD', filename).encode(
        'ASCII', 'ignore').decode('utf-8')

    # Limitar o tamanho do nome do arquivo a 220 caracteres
    filename = filename[:220]

    return filename


# Create your models here.

def upload_to_lancamentos(instance, filename):
    # instance.save()
    # Gere um novo nome de arquivo para evitar conflitos
    if hasattr(instance, 'data_vcto'):
        mes = instance.data_vcto.strftime("%m")
        ano = instance.data_vcto.strftime("%Y")
        dia = instance.data_vcto.strftime("%d")
        descricao = instance.descricao[0:40].replace('/', '_')
    else:
        mes = instance.lcto.data_vcto.strftime("%m")
        ano = instance.lcto.data_vcto.strftime("%Y")
        dia = instance.lcto.data_vcto.strftime("%d")
        descricao = instance.lcto.descricao[0:40].replace('/', '_')

    if (instance.pk is None):
        id = 0
    else:
        id = int(instance.pk)

    numero_aleatorio = random.randint(0, 2**32 - 1)

# Converter para hexadecimal
    numero_hex = format(numero_aleatorio, 'x')

    name_without_extension, extension = os.path.splitext(filename)
    arquivo = sanitize_filename(dia+'_'+mes+'_'+ano+'_'+descricao+'_'+numero_hex).replace('/', '_')
    new_filename = f"doc_{arquivo}{extension}"
    # Construa o caminho completo para upload
    return os.path.join("lancamentos", str(ano), str(mes), new_filename)


def upload_to_movimentos(instance, filename):
    # instance.save()
    # Gere um novo nome de arquivo para evitar conflitos
    mes = instance.data_lcto.strftime("%m")
    ano = instance.data_lcto.strftime("%Y")
    dia = instance.data_lcto.strftime("%d")
    

    name_without_extension, extension = os.path.splitext(filename)
    arquivo = sanitize_filename(dia+'_'+mes+'_'+ano+'_'+instance.historico[0:40]).replace('/', '_')
    new_filename = f"compr_{arquivo}{extension}"

    # Construa o caminho completo para upload
    return os.path.join("movimentos", str(ano), str(mes), new_filename)


def upload_to_documentos_contabeis(instance, filename):
    # instance.save()
    # Gere um novo nome de arquivo para evitar conflitos
    mes = instance.ultimo_dia_mes_referencia.strftime("%m")
    ano = instance.ultimo_dia_mes_referencia.strftime("%Y")
    dia = instance.ultimo_dia_mes_referencia.strftime("%d")
    

    name_without_extension, extension = os.path.splitext(filename)
    arquivo = sanitize_filename(dia+'_'+mes+'_'+ano+'_'+instance.descricao[0:40]).replace('/', '_')
    new_filename = f"outros_docs_{arquivo}{extension}"

    # Construa o caminho completo para upload
    return os.path.join("movimentos", str(ano), str(mes), new_filename)



class PagarReceber(models.Model):
    data_lcto = models.DateField(
        "Data do Lançamento",
        auto_now=True,
        db_index=True
    )
    descricao = models.CharField(
        "Descrição do Lançamento",
        max_length=100
    )
    pessoa = models.ForeignKey(
        Pessoa,
        related_name='lcto_pess',
        on_delete=models.PROTECT,
        verbose_name="Pessoa",

    )
    data_vcto = models.DateField(
        "Data do Vencimento",
        db_index=True
    )

    especie = models.ForeignKey(
        Especie,
        related_name='lcto_especie',
        on_delete=models.PROTECT,
        verbose_name="Espécie do lançamento"
    )
    centro_custo = models.ForeignKey(
        CentrosCustos,
        related_name='lcto_cc',
        on_delete=models.PROTECT,
        verbose_name="Projeto"
    )
    item_orcamento = models.ForeignKey(
        ItensOrcamento,
        related_name='lcto_orc',
        on_delete=models.PROTECT,
        verbose_name="Item Orçamentário"
    )
    nro_docto = models.CharField(
        "Número do Documento",
        null=True,
        blank=True,
        max_length=25
    )

    tipo_documento = models.ForeignKey(
        TiposDocumentos,
        related_name='lcto_tipo_doc',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Tipo de Documento"
    )


    valor_docto = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0
    )

    FORMAS_PGTO = [
        ('BL', 'BOLETO'),
        ('TR', 'TRANSFERÊNCIA'),
        ('ES', 'ESPÉCIE'),
        ('OU', 'OUTRO')
    ]

    forma_pgto = models.CharField("Forma de Pagamento(se houver)",
                                  max_length=2,
                                  choices=FORMAS_PGTO,
                                  blank=True,
                                  null=True,
                                  default=None,
                                  )

    codigo_barras = models.CharField(
        "Código de Barras (se houver)",
        null=True,
        blank=True,
        max_length=100
    )
    conta_pgto = models.ForeignKey(
        DadosPgto,
        related_name='lcto_conta_pgto',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,

        verbose_name="Conta para pagamento(se houver)"
    )

    valor_pago = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,

    )

    STATUS_PGTO = [
        ('AB', 'Aberto'),
        ('PP', 'Parcialmente Pago'),
        ('TP', 'Totalmente Pago'),
    ]

    status = models.CharField(
        "Status do Pagamento",
        max_length=2,
        choices=STATUS_PGTO,
        default='AB',
    )

    image = models.FileField(
        "Arquivo a ser carregado",
        upload_to=upload_to_lancamentos,
        null=True,
        blank=True
    )

    
    data_limite_emissao_nota = models.DateField(
        "Data limite para emissão de nota fiscal (quando aplicável)",
        null=True,
        blank=True,
        help_text="Data limite para emissão de nota fiscal em casos de MEI ou outros casos específicos"
    )


    obs_emissao_notas = models.TextField(
        null=True,
        blank=True,
        help_text="Dados para orientação de emissão de nota fiscal",
        verbose_name="Descriçao para emissão de notas fiscais (quando aplicável)"
    )

    observacoes = models.TextField(
        null=True,
        blank=True,
        help_text="Notas ou comentários sobre este lançamento"
    )

    data_criacao = models.DateTimeField(
        auto_now_add=True, verbose_name="Data de Criação do Lançamento")
    data_atualizacao = models.DateTimeField(
        auto_now=True, verbose_name="Data de Atualização do Lançamento")
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL,
                                null=True, verbose_name="Usuário responsável pelo Lançamento")

    class Meta:
        ordering = ('-data_vcto',)
        verbose_name = "Conta Pagar/Receber"
        verbose_name_plural = "Contas a Pagar/Receber"

    def __str__(self):
        return f"{self.descricao} vencimento {self.data_vcto.strftime('%d/%m/%Y')}"


class LctoDetalhe(models.Model):
    lcto = models.ForeignKey(
        PagarReceber,
        related_name='lcto_detalhe',
        on_delete=models.CASCADE,
        verbose_name="Recibo",
        null=True,
        blank=True
    )


    descricao = models.CharField(
        'Descrição do produto/serviço', max_length=150)
    periodo_qtde = models.CharField('Período/Quantidade', max_length=80)
    valor = models.DecimalField(
        'Valor total do item',
        max_digits=12,
        decimal_places=2
    )

    centro_custo = models.ForeignKey(
        CentrosCustos,
        related_name='lcto_det_cc',
        on_delete=models.SET_NULL,
        verbose_name="Projeto",
        blank=True,
        null=True
    )
    item_orcamento = models.ForeignKey(
        ItensOrcamento,
        related_name='lcto_det_orc',
        on_delete=models.SET_NULL,
        verbose_name="Item Orçamentário",
        blank=True,
        null=True
    )

    class Meta:
        ordering = ('lcto', 'descricao')
        verbose_name = "Item do Lançamento"
        verbose_name_plural = "Itens do Lançamento"

    def __str__(self):
        return f"Detalhes de {self.lcto.descricao} de {self.lcto.data_vcto.strftime('%d/%m/%Y')}"
    

class OutrosArquivosLcto(models.Model):
    lcto = models.ForeignKey(
        PagarReceber,
        related_name='lcto_arquivos',
        on_delete=models.CASCADE,
        verbose_name="Recibo",
        null=True,
        blank=True
    )
    
    image = models.FileField(
        "Arquivo a ser carregado",
        upload_to=upload_to_lancamentos,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('lcto',)
        verbose_name = "Arquivo do Lançamento"
        verbose_name_plural = "Outros Arquivos do Lançamento"

    def __str__(self):
        return f"Arquivo de {self.lcto.descricao} de {self.lcto.data_vcto.strftime('%d/%m/%Y')}"


class MovimentosCaixa(models.Model):



    TIPOS_MOVIMENTOS_CAIXA = [
        ('SI', 'Saldo Inicial'),
        ('TR', 'Transferência entre contas'),
        ('PG', 'Pagamento'),
        ('PR', 'Recebimento'),
    ]

    tipo = models.CharField(
        "Tipo de movimento",
        max_length=2,
        choices=TIPOS_MOVIMENTOS_CAIXA,
        default='PG',
    )

    lcto_ref = models.ForeignKey(
        PagarReceber,
        on_delete=models.SET_NULL,  # Set the field to null when the referenced object is deleted
        related_name='mov_lcto',
        null=True, 
        blank=True,
        verbose_name="Lançamento de Referência"
    )

    data_lcto = models.DateField(
        "Data de Pagamento",
        db_index=True
    )

movimentos/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import MovimentosCaixa, PagarReceber
class MovimentoFormAdmin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MovimentoFormAdmin, self).__init__(*args, **kwargs)
        self.fields['tipo'].widget.attrs['class'] = 'select_tipo'
        self.fields['conta_origem'].widget.attrs['class'] = 'select_conta_origem'
        self.fields['conta_destino'].widget.attrs['class'] = 'select_conta_destino'
     #   self.fields['lcto_ref'].widget.attrs['class'] = 'select_lcto_ref'

    def clean(self):
        tipo = self.cleaned_data['tipo']
        conta_destino = self.cleaned_data['conta_destino']
        conta_origem = self.cleaned_data['conta_origem']
        lcto_ref = self.cleaned_data['lcto_ref']

        if tipo == 'SI':
            if conta_destino is None:
                raise ValidationError("Lançamento tipo saldo inicial exige uma conta destino.")
            if conta_origem is not None:
                raise ValidationError("Lançamento tipo saldo inicial não deve ter conta de origem")
        elif tipo == 'TR':
            if conta_destino is None or conta_origem is None:
                raise ValidationError("Lançamento tipo tranferência exige as contas de origem e destino.")
        elif tipo == 'PG':
            if conta_origem is None or lcto_ref is None:
                raise ValidationError("Lançamento tipo pagamento exige a conta de origem e o lançamento de referência.")
            if conta_destino is not None:
                raise ValidationError("Lançamento tipo pagamento não deve ter conta de destino")
     
        elif tipo == 'PR':
            if conta_destino is None or lcto_ref is None:
                raise ValidationError("Lançamento tipo recebimento exige a conta de destino e o lançamento de referência.")
            if conta_origem is not None:
                raise ValidationError("Lançamento tipo recebimento não deve ter valores de conta de origem")
   


class DateRangeForm(forms.Form):
    start_date = forms.DateField(label='Data de Início')
    end_date = forms.DateField(label='Data de Fim')

movimentos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt_br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar- dark bg-danger fixed-top py-1" id="main-nav">
        <div class="container">
            <a href="{% url 'movimentos:movimentos_caixa_list' %}" class="navbar-brand">
                <h3 class="font-weight-
bold">Movimentação</h3>
            </a>
        </div>
    </nav>
    <div class="container py-5">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://code.jquery.com/ jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb60SsuzixeV4y/
faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/
popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft +2mJbHaEWldlvI910Yy5n3zV9zzTtmI3UksdQRVvoxMfooA
O" crossorigin="anonymous"></script>
        <script src = " {% static 'js/scripts.js' %}" >
    </script>
    <script src="https://cdnjs.cloudflare.com/
ajax/libs/materialize/1.0.0/js/
materialize.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
        integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous">
    </script>
</body>

</html>

movimentos/templates/download_arquivos.html
{% extends "admin/base_site.html" %}

{% block extrastyle %}
<style>
    .custom-form-row {
        margin-bottom: 15px; /* Aumenta o espaçamento entre as linhas */
    }
    .custom-form-row label {
        display: inline-block;
        width: 40px; /* Largura fixa para os labels */
        text-align: left;
        margin-right: 10px; /* Espaçamento entre o label e o campo */
    }
    .custom-form-row input, .custom-form-row select {
        width: 200px; /* Largura dos campos de entrada */
    }
    .tti {
        margin-bottom: 15px;
    }  
</style>
{% endblock %}

{% block content %}
<div class="module">
    <div class="tti"><strong>Digite o mês e o ano desejados para download dos documentos para contabilidade:</strong></div>
    <form action="{% url 'movimentos:download_arquivos' %}" method="post" class="form">
        {% csrf_token %}
        <div class="custom-form-row">
            <label for="mes">Mês:</label>
            <input type="number" name="mes" id="mes">
        </div>
        <div class="custom-form-row">
            <label for="ano">Ano:</label>
            <input type="number" name="ano" id="ano">
        </div>
        <div class="custom-form-row">
            <input type="submit" value="Enviar">
        </div>
    </form>
</div>
{% endblock %}

movimentos/templates/fechamento.html
{% extends "admin/base_site.html" %}

{% block extrastyle %}
<style>
    .custom-form-row {
        margin-bottom: 15px; /* Aumenta o espaçamento entre as linhas */
    }
    .custom-form-row label {
        display: inline-block;
        width: 50px; /* Largura fixa para os labels */
        text-align: left;
        margin-right: 10px; /* Espaçamento entre o label e o campo */
    }
    .custom-form-row input, .custom-form-row select {
        width: 200px; /* Largura dos campos de entrada */
    }
    .tti {
        margin-bottom: 15px;
    }   
</style>
{% endblock %}

{% block content %}
<div class="module">
    <div class="tti"><strong>Digite o mês e o ano desejados para geração do livro caixa:</strong></div>
    <form action="{% url 'movimentos:relatorio_fechamento' %}" method="post" class="form">
        {% csrf_token %}
        <div class="custom-form-row">
            <label for="mes">Mês:</label>
            <input type="number" name="mes" id="mes">
        </div>
        <div class="custom-form-row">
            <label for="ano">Ano:</label>
            <input type="number" name="ano" id="ano">
        </div>
        <div class="custom-form-row">
            <label for="conta">Conta:</label>
            <select name="conta" id="conta">
                <option value="all">Relatório Geral</option>
                {% for conta in contas %}
                    <option value="{{ conta.id }}">{{ conta.nome }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="custom-form-row">
            <input type="submit" value="Enviar">
        </div>
    </form>
</div>
{% endblock %}

movimentos/templates/form_movimentos.html
{% extends "admin/change_form.html" %}

{% block submit_buttons_bottom %}
    {% if 'origem' in request.GET %}
        {% if perms.movimentos.change_movimentoscaixa %}
        <input type="submit" value="Quitar" name="_quitar" />
        {% endif %}
    {% else %}
        <!-- Botões padrões -->
        {{ block.super }}
    {% endif %}
{% endblock %}

movimentos/templates/form_pagarreceber.html
{% extends "admin/change_form.html" %}

{% block submit_buttons_bottom %}
    {{ block.super }}
    {% if perms.movimentos.change_movimentoscaixa %}
    <input type="submit" name="_salvar_e_quitar" value="Salvar e Quitar" class="default">
    {% endif %}
{% endblock %}

movimentos/templates/relatorio_detalhado.html
{% extends "admin/base_site.html" %}

{% block extrastyle %}
<style>
    .custom-form-row {
        margin-bottom: 15px; /* Aumenta o espaçamento entre as linhas */
    }
    .custom-form-row label {
        display: inline-block;
        width: 120px; /* Largura fixa para os labels */
        text-align: left;
        margin-right: 10px; /* Espaçamento entre o label e o campo */
    }
    .custom-form-row input, .custom-form-row select {
        width: 200px; /* Largura dos campos de entrada */
    }
    .tti {
        margin-bottom: 15px;
    }   
</style>
{% endblock %}

{% block content %}
<div class="module">
    <div class="tti"><strong>Preencha com os filtros desejados:</strong></div>
    <form action="{% url 'movimentos:relatorio_final_detalhado' %}" method="post" class="form">
        {% csrf_token %}
        <div class="custom-form-row">
            <label for="mes">Mês:</label>
            <input type="number" name="mes" id="mes">
        </div>
        <div class="custom-form-row">
            <label for="ano">Ano:</label>
            <input type="number" name="ano" id="ano">
        </div>
        <div class="custom-form-row">
            <label for="centro_custo">Projeto:</label>
            <select name="centro_custo" id="centro_custo">
                <option value="all">Todos</option>
                {% for centro_custo in centros_custos %}
                    <option value="{{ centro_custo.id }}">{{ centro_custo.descricao }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="custom-form-row">
            <label for="orcamento">Item Orçamentário:</label>
            <select name="orcamento" id="orcamento">
                <option value="all">Todos</option>
                {% for orcamento in orcamentos %}
                    <option value="{{ orcamento.id }}">{{ orcamento.descricao }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="custom-form-row">
            <input type="submit" value="Enviar">
        </div>
    </form>
</div>
{% endblock %}

movimentos/templates/relatorio_fechamento.html
{% extends "admin/base_site.html" %}
{% load static %}


{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'fechamento.css' %}" media="screen" />
    <p> {{ conta }} </p>
    <p> {{ conta.nome }} </p>
    <p>Visualização Livro Caixa mês: {{ mes }} ano: {{ ano }} </p>
    <p>Saldo do mês anterior (em R$): {{ soma }}</p>
   

    <form id="botoes" name="botoes" method="POST">
        {% csrf_token %}
        <input type="hidden" name="saldo" value="{{ saldo }}">
        <input type="hidden" name="conta" value="{{ conta.nome }}">

        <input type="hidden" name="soma" value="{{ soma }}">
        <input type="hidden" name="mes" value="{{ mes }}">
        <input type="hidden" name="ano" value="{{ ano }}">
        <input type="hidden" name="cabecalho" value="{{ cabecalho }}">
        <input type="hidden" name="query" value="{{ query }}">
        {% if conta != 'Relatório Geral' %}
             <input type="hidden" name="conta" value="{{ conta.nome }}">
        {% else %}
            <input type="hidden" name="conta" value="{{ conta }}">
        {% endif %}
        <table>
            <tr>
                <td>
                    <input type="submit" id="pdf" value="Gerar Pdf"></input>
                </td>
                <td>
                    <input type="submit" id="excel" value="Gerar Excel"></input>
                </td>
            </tr>
            
        

        <table>
            <tr class="destaque">
                {% for coluna in cabecalho %}
                <td> {{ coluna }} </td>
                
                {% endfor %}
            </tr>
            <tr class="destaque">
                {% for i in cabecalho %}
                    {% if forloop.first %}
                        <td> SALDO INICIAL </td>
                    {% elif forloop.last %}
                        <td class='ultima_coluna'> {{ soma }} </td>
                    {% else %}
                        <td></td>
                    {% endif %}

                {% endfor %}
            </tr>
            {% for linha in query %}
                        <tr>
                {% for col in linha %}
               
                {% if forloop.last %}
                    <td class="ultima_coluna">{{ col }}</td>
                {% else %}
                    <td>{{ col }}</td>
                {% endif %}
                {% endfor %}
            </tr>
            
            {% endfor %}
            <tr class="destaque">
                {% for i in cabecalho %}
                    {% if forloop.first %}
                        <td> SALDO FINAL </td>
                    {% elif forloop.last %}
                        <td class='ultima_coluna'> {{ saldo }} </td>
                    {% else %}
                        <td></td>
                    {% endif %}

                {% endfor %}
            </tr>

            
        </table>
    </form>
    <script src="{% static 'buttons.js' %}"></script>
{% endblock %}

movimentos/templates/relatorio_final_detalhado.html
{% extends "admin/base_site.html" %}
{% load static %}


{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'fechamento.css' %}" media="screen" />
    <p><strong> Projeto: {{ centro_custo }} </strong></p>
    <p><strong> Item Orçamentário: {{ orcamento }} </strong> </p>
    <p><strong>Relatório de entradas e saídas por Projeto/Item Orçamentário mês: {{ mes }} ano: {{ ano }} </strong></p>
    <p>Os lançamentos apresentados são base caixa, ou seja, os que efetivamente foram recebidos e pagos no mês selecionado.</p>
    {% if soma != '0,00' %}
    <p>Saldo do mês anterior (em R$): {{ soma }}</p>
    {% else %}
    <p> Foram selecionados todos os projetos, por isso, o saldo inicial será zerado para que apareçam apenas as entradas e saídas do mês selecionado para o item orçamentário selecionado. </p>
    {% endif %}

    <form id="botoes" name="botoes" method="POST">
        {% csrf_token %}
        <input type="hidden" name="saldo" value="{{ saldo }}">
        <input type="hidden" name="centro_custo" value="{{ centro_custo }}">
           <input type="hidden" name="orcamento" value="{{ orcamento }}">
        <input type="hidden" name="soma" value="{{ soma }}">
        <input type="hidden" name="mes" value="{{ mes }}">
        <input type="hidden" name="ano" value="{{ ano }}">
        <input type="hidden" name="cabecalho" value="{{ cabecalho }}">
        <input type="hidden" name="query" value="{{ query }}">
        <input type="hidden" name="conta" value="Rel Detalhado">
      
        <table>
            <tr>
                <td>
                    <input type="submit" id="pdf" value="Gerar Pdf"></input>
                </td>
                <td>
                    <input type="submit" id="excel" value="Gerar Excel"></input>
                </td>
            </tr>
            
        

        <table>
            <tr class="destaque">
                {% for coluna in cabecalho %}
                <td> {{ coluna }} </td>
                
                {% endfor %}
            </tr>
            <tr class="destaque">
                {% for i in cabecalho %}
                    {% if forloop.first %}
                        <td> SALDO INICIAL </td>
                    {% elif forloop.last %}
                        <td class='ultima_coluna'> {{ soma }} </td>
                    {% else %}
                        <td></td>
                    {% endif %}

                {% endfor %}
            </tr>
            {% for linha in query %}
                        <tr>
                {% for col in linha %}
               
                {% if forloop.last %}
                    <td class="ultima_coluna">{{ col }}</td>
                {% else %}
                    <td>{{ col }}</td>
                {% endif %}
                {% endfor %}
            </tr>
            
            {% endfor %}
            <tr class="destaque">
                {% for i in cabecalho %}
                    {% if forloop.first %}
                        <td> SALDO FINAL </td>
                    {% elif forloop.last %}
                        <td class='ultima_coluna'> {{ saldo }} </td>
                    {% else %}
                        <td></td>
                    {% endif %}

                {% endfor %}
            </tr>

            
        </table>
    </form>
    <script src="{% static 'buttons.js' %}"></script>
{% endblock %}